server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/edusmart_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

langchain4j.open-ai.chat-model.api-key=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
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini